YottaDB/YottaDB

sr_port/op_fnquery.c
sr_port/op_fnreversequery.c

Release Note
-------------
$query(lvn) issues a MAXSTRLEN error if the length of the string it is about to return exceeds the maximum string
length (1Mb) supported by YottaDB. In previous versions of YottaDB, one could construct strings of arbitrary length
using the out-of-design string returned by $query(lvn) and that could in turn lead to abnormal process termination
(e.g. SIG-11). (YDB#25)

[YDB#25] [NARS] [estess] Fix $query (and reverse $query) to never return a result greater than MAX_STRLEN

---

sr_port/gdsfhead.h
sr_port/merrors.msg
sr_x86_64/merrors_ctl.c

Release Note
-------------
The OFRZAUTOREL message displays the full path of the database file name instead of a potentially-ambiguous region name.
Test
----
* E_ALL run to ensure no regressions.
* v63001/gtm8362 subtest enhanced to search for OFRZAUTOREL message coming only from the test output directory
of interest. Previously, if two concurrent gtm8362 tests were running, it was possible for one test
to be confused by the OFRZAUTOREL message of another test (since the message only indicated the region
name). Now the OFRZAUTOREL message contains the test output directory path so it can clearly identify
messages that correspond to its database file of interest.

[NARS1] [estess] OFRZAUTOREL message should indicate database file full path instead of ambiguous region name #47

---

sr_i386/incr_link.c
sr_i386/obj_file.c
sr_linux/release_name.h
sr_port/gdsbt.h
sr_port/gtm_assert.c
sr_port/gtm_assert2.c
sr_port/gvcst_init.c
sr_port/mu_dwngrd_header.c
sr_port/mu_upgrd_header.c
sr_port/mupip_backup.c
sr_port/mupip_downgrade.c
sr_port/mupip_upgrade.c
sr_port_cm/gtcm_protocol.c
sr_unix/dse_help.c
sr_unix/gds_rundown.c
sr_unix/gtmsecshr.c
sr_unix/gvcst_init_sysops.c
sr_unix/incr_link.c
sr_unix/jnlpool_init.c
sr_unix/list_file.c
sr_unix/mu_rndwn_all.c
sr_unix/mu_rndwn_file.c
sr_unix/mu_rndwn_replpool.c
sr_unix/recvpool_init.c
sr_unix/repl_inst_dump.c
sr_unix/secshr_client.c
sr_unix_cm/omi_prc_conn.c
sr_x86_64/obj_filesp.c

Release Note
-------------
A VERMISMATCH error now reports the YottaDB release # and not the GT.M release #.
Test
-----
* E_ALL run many times to ensure no regressions.
README
-------
Almost all usages of gtm_release_name were examined and changed to ydb_release_name.
The only place left was where we report $ZVERSION which does need to use gtm_release_name.
This meant that database shared memory created by a GT.M version cannot be attached to by a
YottaDB version even if both the versions have the same shared memory layout (because the
shared memory would have the GT.M version # stored whereas the YottaDB version expects the
YottaDB release # to be stored). Similarly, the jnlpool, receive pool and the object file
now have the YottaDB release # stored.

[YDB#50] [NARS1] [estess] Change all GT.M release name usages (e.g. now_running field in db shared memory) to YottaDB release names

---

sr_unix/errorsp.h

```
The v63000/gtm8394 subtest failed an assert with the following stack trace.
#0  0x00007f3f038734c7 in kill () from /usr/lib64/libc.so.6
#1  0x00000000006c2413 in gtm_dump_core () at R110/sr_unix/gtm_dump_core.c:69
#2  0x00000000006d5dd0 in gtm_fork_n_core () at R110/sr_unix/gtm_fork_n_core.c:211
#3  0x0000000000695b5b in ch_cond_core () at R110/sr_unix/ch_cond_core.c:59
#4  0x000000000087e6ba in rts_error_va (csa=0x0, argcnt=7, var=0x7f3ef864e178) at R110/sr_unix/rts_error.c:153
#5  0x000000000087dca4 in rts_error_csa (csa=0x0, argcnt=7) at R110/sr_unix/rts_error.c:85
#6  0x0000000000916610 in hashtab_rehash_ch (arg=150373340) at R110/sr_port/hashtab_rehash_ch.c:33
#7  0x000000000087ec12 in rts_error_va (csa=0x0, argcnt=5, var=0x7f3ef864e438) at R110/sr_unix/rts_error.c:153
#8 …
```

[NARS1] [estess] Handle the possibility of an UNWIND in a condition handler in threaded code

---

CMakeLists.txt
README.md
sr_unix/configure.gtc
sr_unix/ydbinstall.sh

README.md : Make it easier to build and install YottaDB from source
ydbinstall.sh
a) Fix more occurrences of GT.M/gtm to YottaDB/ydb
b) Make help more useful by printing some example usages
c) Do not print full help in case of an error. Just point to help so actual error is highlighted.
d) Add support for Linux on ARMV7L
e) Fix bug (default case label should be "*" and not "default")
f) Derive YottaDB release # (not GT.M version #) if ydbinstall and mumps are bundled together
g) Issue error messages if wget fails

Make it easier to install YottaDB from a source or binary tarball

---

CMakeLists.txt

This reverts commit 29ac63a4000ce3cbbc4c57ffb8fef511eee49695. This is because at least mupip
currently does a dlopen() of shared libraries (e.g. libgtmtls.so) which in turn open shared libraries
(e.g. libgtmcryptutil.so) that in turn use symbols (e.g. "gtm_free") which need to be resolved
back in the mupip executable. And -rdynamic is needed to let that resolve fine.

Revert "[YDB#66] [NARS1] [shabiel] Do not use -rdynamic for C link-time flags (default in cmake) as that bloats executable sizes unnecessarily"

---

sr_unix/configure.gtc
sr_unix/ydbinstall.sh

* If used interactively, do not turn on sh verbose mode as it prints a lot of output.
Use that only for invocations through ydbinstall which redirect the output to a file anyways.
* If RemoveIPC=no is not set in /etc/systemd/logind.conf, and configure script is used interactively
(instead of invoking it through ydbinstall.sh), a function to prompt user for a Y or N answer
(yes_or_no) was missing. Add it.
* For reasons not yet known, ld in Linux on the ARM does not create a usable shared library
(e.g. libgtmutil.so) when linking compiled M routines in. Use cc instead which works fine.

Various fixes to the configure script

---

sr_unix/ydbinstall.sh

* The example usages (displayed by running ydbinstall.sh --help) are now enhanced.
* One displayed example (ydbinstall.sh --gtm V6.3-002) installed GT.M at /usr/local/lib/fis-gtm/_x86_64
and is now fixed to install at /usr/local/lib/fis-gtm/V6.3-002_x86_64

[NARS1] [ksbhaskar] Enhancements to ydbinstall.sh --help to display the command for UTF-8 install; Fix GT.M version installdir

---

sr_unix/configure.gtc

Having a utf8 filename in $gtm_dist/utf8 soft link back to $gtm_dist is a recipe for soft link recursion and can cause operational issues (e.g. backups). So avoid that.

During utf8 install, avoid soft link recursion in $gtm_dist/utf8/utf8

---

sr_unix/ydbinstall.sh

Previously, the following install of a GT.M version used to incorrectly say YottaDB version V6.3-002.
$ ydbinstall.sh --gtm
YottaDB version V6.3-002 installed successfully at /usr/local/lib/fis-gtm/V6.3-002_x86_64
Now it correctly says the following
GT.M version V6.3-002 installed successfully at /usr/local/lib/fis-gtm/V6.3-002_x86_64

[#99] [NARS1] [ksbhaskar] Install success message should only say YottaDB if installing a YottaDB version

---

sr_port/mdef.h
sr_port/op_open.c
sr_port/op_read.c
sr_port/op_readfl.c

Basically, a READ Y:.0001 hangs indefinitely. But a READ Y:.001 times out correctly.
This is an issue introduced in GTM-5250 as part of GT.M V6.3-002.
The MV_FORCE_MSTIMEOUT macro is what converted the fractional timeout into an integer # of milliseconds.
This worked correctly if the mvtype of the mval holding the timeout value is MV_INT (which is the case
even for fractions upto 3 decimal digits). But for fractions greater than 3 decimal digits, the mvtype
would not be MV_INT but instead MV_NM and in that case, the macro was incorrectly setting the timeout
to be MAXPOSINST4 (2Gi) milliseconds (~ 24 days). This is now fixed by doing a mval2double() call to
determine the real value and converting that into milliseconds and capping that timeout with MAXPOSINT4.
The affected commands are …

[#100] Do not treat fractional timeouts with more than 3 digits after the decimal point as a 2Gi msec timeout

---

sr_unix/gtmci.c
sr_unix/gtmshr_symbols.exp
sr_unix/gtmxc_types.h
sr_unix/op_fnfgncal.c

Below are the issues.
1) Various modules : The prior commit changed names of functions to have ydb_ prefix instead
of the gtm_ prefix. But the latest java plugin has the function names with the gtm_ prefix
hardcoded and since we do not want to maintain the java plugin at this point in time,
we need to provide function names with both the ydb_ and gtm_ prefix.
2) gtmci.c : The prior commit had added a call to op_exfunret() in the ydb_cij() function.
But this was in the wrong place (should have been in the "if" block instead of the "else"
block). This is now fixed like how it is in the ydb_ci_exec() function.
3) op_fnfgncal.c : The prior commit had changed the name "gtm_xcj" to be "ydb_xcj". But the
java plugin is the one that defines this function and, again since we want to avoid having …

[#59] Fix a few issues (in a prior #59 commit) exposed by the java test

---

sr_port/gtm_threadgbl_init.c
sr_unix_cm/gtcm_server_main.c

While trying to check whether the MIXIMAGE error (introduced as part of a recent #33 commit)
is issued correctly, a couple of code issues were identified.
1) gtm_threadgbl_init() is invoked by the GTM_THREADGBL_INIT macro and that is invoked only
once per image (i.e. once in mumps, once in mupip etc.). And so it had a check that
gtm_threadgbl be NULL and issued an error otherwise. But it is possible in case the process
has already loaded an image and is attempting to load another image that gtm_threadgbl is
non-NULL. This is a case where a MIXIMAGE error is about to be issued by common_startup_init()
once we return from this function. So this check is now changed so we return if non-NULL.
2) gtcm_server_main() set "ctxt" global variable to NULL at function entry. This caused an
error …

[#33] Fix code to let MIXIMAGE error (recently introduced) be issued when appropriate

---

sr_linux/platform.cmake

It was observed that caller_id.c did not record the caller function information in debug arrays
(e.g. cs_addrs->nl->crit_ops_array[].call_from) in YottaDB for ARM Linux whereas it did in YottaDB
for x86_64 Linux. Turns out this was because backtrace() returned 0 on ARM Linux.  And that in
turn was due to gcc default options not including -funwind-tables.  This is now fixed by adding
this option explicitly for all platforms (including x86_64 Linux) in case a future version of
gcc there removes this flag by default.  After the change to add this compiler flag, backtrace()
returns a non-zero value and caller_id now works.
Since this is noticeable only in debug builds of YottaDB, this does not have a separate issue#.

caller_id now works in YottaDB for ARM Linux (just like it does on YottaDB for x86_64 Linux)

---

sr_port/mur_back_process.c
sr_port/mur_forward_play_cur_jrec.c
sr_unix/jnlext_merge_sort_prepare.c

mur_back_process.c : It is possible a NULL record got written on behalf of a TP transaction's records in one region
(by "jnl_phase2_salvage", when a process gets abnormally killed) but some regions of the same TP transaction have
those records in tact. In this scenario, mur_back_process.c currently issues a DUPTOKEN error in pro and an assert
failure in dbg. This is now fixed to treat all records of this transaction across multiple regions (NULL or non-NULL
type of records) as belonging to the same transaction and not issue a DUPTOKEN error.
mur_forward_play_cur_jrec.c : Ensure a NULL record written on behalf of a TP transaction's records in one region
gets treated as a broken transaction and ends up in the broken transaction file).
jnlext_merge_sort_prepare.c : Use jnl seqno as token for …

[#122] Fix various issues with MUPIP JOURNAL ROLLBACK in handling NULL type of journal records

---

sr_port/anticipatory_freeze.h
sr_port/gdsfhead.h
sr_port/gtm_libaio.h
sr_unix/aio_shim.c
sr_unix/gtmio.h
sr_unix/wcs_wt_restart.c

The system header file involved is /usr/include/linux/aio_abi.h and the structure involved is struct iocb.
This header file is found in the
linux-libc-dev package on Ubuntu/Debian
linux-api-headers package on Arch
kernel-headers package on RHEL/CentOS
The version of linux-api-headers package afer the system patch was 4.14.8-1.
This had a different layout than the one which was copied over to the YottaDB codebase.
And that caused compile time errors. To avoid this issue (and future issues with structure layout changes),
the change done was to keep the system "struct iocb" structure as a member of the aiocb structure
defined in the YottaDB codebase. Because of this change, some usages of members in the system iocb
structure had to be changed to have an extra structure member dereference. …

Get YottaDB builds working on Arch linux where system iocb structure layout changed recently after a system patch

---

sr_unix/gtmrecv_poll_actions.c

This is an issue observed from a test failure (in the merge/tp_stress subtest) during internal
testing. The primary failure symptom was an assert failure in the source server
%GTM-F-ASSERT, Assert failed in sr_unix/gtmsource_process_ops.c line 1167 for expression (FALSE)
The source server assert failed because it was expecting a REPL_INSTINFO message
(msgtype == 29) but instead got a REPL_CMP2UNCMP message (msgtype == 25).
The merge/tp_stress subtest induces a REPL_CMP2UNCMP situation using white-box code so the fact
that the receiver sent a REPL_CMP2UNCMP message is not surprising. But the timing of the send
is where the problem is.
The issue is that we maintain the fact that a CMP2UNCMP message needs to be sent in a static
variable "send_cmp2uncmp" and had set it to TRUE (in …

[#136] Reset connection-related state soon after connection gets reset; Not doing so could affect new connection when it gets established

---

sr_port/cre_jnl_file.c

The issue was a regression in GT.M V6.3-002 (most likely due to GTM-8543) where the file name
and length are passed out of order.

[#118] SIG-11 from MUPIP SET JOURNAL in case renaming older journal file (with timestamp suffix) fails (e.g. permission issues)

---

sr_armv7l/op_bkpt.s
sr_port/op.h
sr_port/op_zst_over_retarg_helper.c
sr_port/op_zstep.c
sr_port/op_zstepretarg_helper.c
sr_x86_64/op_bkpt.s

ZSTEP OVER operates (in op_zstep.c) by noting down the current $zlevel in the global variable
"zstep_level" and changing the transfer table so "opp_zst_over_retarg" is invoked instead of
"op_retarg" but otherwise leaves the transfer table untouched so op_linestart etc. are still
executed as normal as long as nested levels of M frames are invoked. If the nested level
invocation is an extrinsic function (that returns a value) "opp_zst_over_retarg" is invoked as
part of returning from that level. "opp_zst_over_retarg" (in op_bkpt.s) checks if "zstep_level"
is the same as frame_pointer->old_frame_pointer and if so, it calls "op_zstepret" to fix the
transfer table so "op_zst_st_over" is invoked instead of "op_linestart" (and so on). That is,
the ZSTEP action which was hidden during nested …

[#141] Fix ZSTEP OVER and ZSTEP OUTOF to work if an extrinsic function returns using QUIT @ syntax

---

sr_port/gtm_env_init.c
sr_port/gtm_threadgbl_defs.h
sr_port/gtm_threadgbl_init.c
sr_port/merrors_ctl.c
sr_unix/gtm_getmsg.c
sr_unix/gtm_logicals.h

If the env var is unset, the default prefix is "YDB"
If the env var is set to a string that is less than or equal to 31 bytes long, the env var
value is taken as the message prefix.
If the env var is set to a string that is more than 31 bytes long, the default prefix of "YDB"
is assumed.
Note the this env var only affects error messages in merrors.msg and not other the errors in
other .msg files (e.g. ydberrors.msg, gdeerrors.msg etc.)
Also the ydb_msgprefix initialization is done at the top of gtm_env_init() (instead of the
usual practice which is to add it to the end of the file) to ensure user-specified msgprefix
is honored if/when issuing errors inside gtm_env_init().

[#97] ydb_msgprefix env var controls YottaDB message prefix for merrors.msg errors (default is "YDB")

---

sr_port/op_div.c
sr_port/op_idiv.c
sr_port/op_mul.c

Not doing so could cause a later use of this result mval in a division operation to issue a
fatal SIGINTDIV error (instead of a user-trappable DIVZERO error). This is because op_div.c
and op_idiv.c assume that if the divisor has the MV_INT bit not set, it is a non-zero value.
The MV_INT bit set is achieved by checking explicitly if both the mantissa (m[0] and m[1])
are zero and if so setting the mval to "literal_zero".

[#145] Ensure MV_INT bit is set if result of multiply or divide of two non-integer numeric quantities is 0

---

sr_linux/platform.cmake

Use the YDB_SOURCE_DIR cmake variable to get the path to ydbmerrors.h
instead of a hardcoded relative path

Change relative path to ydbmerrors to use src directory

---

sr_unix/iott_close.c
sr_unix/iott_open.c
sr_unix/iott_rdone.c
sr_unix/iott_readfl.c
sr_unix/iott_recall_array_add.c
sr_unix/iott_use.c
sr_unix/iottdef.h

M READ Editing is a pre-existing feature in YottaDB that is enabled with USE $PRINCIPAL:EDITING
But that maintained only a history of 1 recall item. That is, a cursor up in a READ X command
would recall the most recently entered input to a previous READ X, READ *X or READ X# command.
This change enhances that history from 1 line to 99 lines. Just like direct mode operates.
Relevant details
-----------------
* A circular buffer tt_ptr->recall_array is maintained for past terminal read inputs (99).
* The global tt_ptr->recall_index points to the current index into this array.
* READ X# (iott_readfl), READ *X (iott_rdone) and READ X (iott_read which in turn calls iott_readfl)
commands all share the same history.
* Cursor UP goes back in history (from most recently added item back to oldest …

[#83] Enhance M READ Editing in terminal to have history of 99 lines (same as direct mode)

---

sr_port/gtm_threadgbl_defs.h
sr_port/op_unwind.c
sr_port/unw_mv_ent.c
sr_unix/gtm_trigger.c

gtm_trigger_fini() is passed a parameter indicating whether the unwind is forced or not.
But this information is not currently passed to op_unwind() and in turn unw_mv_ent()
which is where the MVST_TRIGR mv_stent is unwound. As part of that unwind, we currently
reset the condition handler stack unconditionally (active_ch, ctxt etc.). But this is
not the right thing to do if the unwind is not forced. An example invocation is from
mdb_condition_handler() using the TRIGGER_BASE_FRAME_UNWIND_IF_NOMANSLAND macro (which
will do the trigger base frame unwind if we are in what is defined as the no-mans-land).
In that case, mdb_condition_handler() is about to do an UNWIND soon after the base frame
unwind and will be caught by surprise if the condition handler stack is reset from under
itself (e.g. …

[#169] Restore condition handler stack on trigger frame unwind only if it is a forced unwind

---

Dockerfile

The gtm script is a symlink to the ydb script for compatibility
purposes only. Update the docker file to use the script directly
instead of relying upon the symlink.

Change Dockerfile to run ydb script instead of gtm script

---

sr_port/io_rundown.c
sr_port/op_zsystem.c
sr_unix/continue_handler.c
sr_unix/dm_read.c
sr_unix/iott_open.c
sr_unix/iott_rdone.c
sr_unix/iott_readfl.c
sr_unix/iott_use.c
sr_unix/iott_write.c
sr_unix/iottdef.h
sr_unix/op_zedit.c
sr_unix/resetterm.c
sr_unix/setterm.c

There are two issues.
1. At process startup, YottaDB currently changes a few terminal characteristics
if the principal device is a terminal. But if a C program that invokes a call-in is
how the YottaDB initialization occurred, process exit currently does not reset these
characteristics. This leaves the terminal in a weird state. For example, character
echo is disabled etc. A "stty sane" is needed to get the terminal back to normal.
This is an issue in GT.M and is reported at https://sourceforge.net/p/fis-gtm/bugs/60/.
2. The terminal changes are actually needed in case a READ or WRITE from/to the terminal
(including direct mode) happens. But this is done unconditionally. This is best avoided.
The fixes are
1. Fix io_rundown to do a resetterm() in case process is exiting and we do not do a …

[#184] C program that invokes call-ins should undo any terminal characteristic changes when process exits

---

sr_port/mdb_condition_handler.c

This reverts a change made in GTM-8003 for V6.2-000. But the v62000/gtm8003 test still passes without it.

[#186] Drive ctrl-C handlers correctly, don't dispatch M handlers in direct mode

---

sr_unix/mutex.c

This is a debug-only issue that requires kill -9s of two online rollback processes
in specific functions (mur_process_intrpt_recov() and wcs_recover()) that eventually
causes a third online rollback to assert fail.
While the actual fix to the assert failure is a modification of the assert in
mutex_salvage() (sr_unix/mutex.c), an additional change was done here to distinguish
kill -9 of a wcs_recover vs a commit both of which result in early_tn != curr_tn.
The salvage part needs to happen only for the commit cleanup. Not sure if this change
has implications for pro builds (i.e. is user visible or not) but not spending any
more time on this kill-9 usecase now since kill -9s are not offically supported anyways.
Below is the test case that demonstrates the issue.
```
> ver v63003a_r120 d
> …
```

Handle edge case with multiple kill -9s on online rollback processes

---

sr_unix/mumps.cmake

Below is an example build where gde.m had an error which was logged in the build log.
```
i $p($zs,",",3,999)[="-E-IOEOF, Attempt to read past an end-of-file" d
At column 22, line 67, source module /Distrib/YottaDB/V998/dbg/GDE.m
%YDB-E-RHMISSING, Right-hand side of expression expected
```
But the build incorrectly ran fine (0 exit status) due to lack of error checking
in the mumps.cmake script.

Fail the cmake build if there is an error in the mumps.cmake custom command invocation

---

sr_unix/get_src_line.c

Currently if a routine line returned by $TEXT() contains a carriage return ($C(13)), it is returned with the line. This can happen if a source file is imported from Windows but is not converted to UNIX newline methods (no CR needed). The code already removed the newline ($C(12)) character but this modification adds the removal of CR characters too.

[#159] If $TEXT() line ends in $C(13), remove it from the returned line

---

README.md

"Development" was misspelled as "developement" and "prerequisite" as "pre-requisite." See https://www.merriam-webster.com/dictionary/prerequisite
Thanks much!

Fix spelling in README.md "how to build" section

---

sr_port/gdsfhead.h
sr_port/gvcst_expand_key.h
sr_port/op_tcommit.c
sr_port/tp_hist.c
sr_port/tp_restart.c
sr_port/tp_tend.c

* The TPRESTART syslog message relies on all cdb_sc_blkmod occurrences invoking the
TP_TRACE_HIST_MOD macro. One case in gvcst_expand_key.h was missed out. Now fixed.
The user-visible impact of this is that some L type of restarts in TP could
print a potentially incorrect "type:" field because the type was not set as part of
the current restart (but are using a leftover value of TREF(blkmod_fail_type) from a
prior restart in the same process).
* In case a cdb_sc_blkmod happens in op_tcommit, it used to be classified as a
tp_blkmod_t_qread which is misleading since this is not the usual invocation of
"t_qread" before the TCOMMIT command. So make this a new type "tp_blkmod_op_tcommit".
This is now recognized by tp_restart() to decide whether to print unsubscripted
gvn or not in the …

[#207] Some more fixes to TPRESTART syslog message accuracy

---

sr_armv7l/GTMDefinedTypesInitDebug.m
sr_armv7l/GTMDefinedTypesInitRelease.m
sr_port/db_auto_upgrade.c
sr_port/dse_dmp_fhead.c
sr_port/gdsdbver_sp.h
sr_port/gdsfhead.h
sr_port/mdef.h
sr_port/mu_reorg.c
sr_port/mupip_set.c
sr_port/repl_comm.c
sr_port/time_calc.c
sr_unix/gt_timers.c
sr_unix/gtm_rel_quant.h
sr_unix/gtmrecv_fetchresync.c
sr_unix/mupip_cmd.c
sr_unix/mupip_set_file.c
sr_unix/op_zut.c
sr_unix/sleep.h
sr_x86_64/GTMDefinedTypesInitDebug.m
sr_x86_64/GTMDefinedTypesInitRelease.m

* A new field "reorg_sleep_nsec" is introduced in the database file header (sgmnt_data).
Any MUPIP REORG process will check this value and if non-zero will sleep for the
specified # of nanoseconds before processing every block in the database. This field
can be changed with a MUPIP SET -REORG_SLEEP_NSEC= command which can be run while
the reorg process is still running (i.e. the command does not require standalone access
to the database file). This lets the user try out different sleeps in the same reorg
process in case it runs for a long time.
* DSE DUMP -FILE displays the current setting of reorg_sleep_nsec.
* Because of the new field in the file header, the database minor version needed change.
* And GTMDefinedTypesInit* files needed to be regenerated (to ensure PEEKBYNAME works
with …

[#233] Reduce IO impact of MUPIP REORG with new -REORG_SLEEP_NSEC qualifier

---

sr_port/gtmsource_ctl_init.c
sr_port/wbox_test_init.h
sr_unix/jnl_file_open.c

Background
-----------
The v62000_1/gtm8086 subtest failed because the source server terminated prematurely with a JNLSWITCHRETRY error.
The test drives a lot of processes doing updates to the db/jnls with a small autoswitchlimit value so journal file switches happen frequently (once or twice a second).
After one journal switch has happened, the test turns off write permissions to the directory housing the journal files ("jnldir").
Since this test runs with replication and has instance freeze turned on, the test expects the instance to be frozen when a journal switch happens after write permissions have been turned off (that did freeze the instance in this test run).
Soon after the test turns write permissions back on "jnldir".
In this test run though, it so happened that the source …

[#235] Ensure source server never terminates with a JNLSWITCHRETRY error

---

sr_unix/gtmrecv_poll_actions.c

Issue #136 moved all state related information in gtmrecv_poll_actions.c into a structure
variable "curr_conn_state". But there was another global variable "gtmrecv_send_cmp2uncmp"
which was set in gtmrecv_process.c and was the same as "curr_conn_state.send_cmp2uncmp"
which meant whenever "curr_conn_state.send_cmp2uncmp" got cleared (due to the memset
changed introduced in #136), "gtmrecv_send_cmp2uncmp" should have also been cleared.
Not doing so, meant it was still possible for a stale old connection related state
variable to be carried over to a new connection resulting in an assert failure in the
source server in rare cases (just like #136) in dbg or a connection loss and reconnect
sequence in pro (this did happen in one in-house test failure). This is now fixed
so both variables are …

[#237] Reset one more connection-related state information (missed out in #136) soon after connection gets reset

---

sr_port/dse_chng_fhead.c
sr_port/gtm_string.h
sr_port/iosocket_listen.c
sr_port/op_fnzsocket.c
sr_unix/cli_parse.c
sr_unix/gtm_tls_impl.c
sr_unix/gtmcrypt.h
sr_unix/gtmcrypt_dbk_ref.c
sr_unix/gtmcrypt_pk_ref.c
sr_unix/gtmcrypt_util.c
sr_unix/jnl_prc_vector.c
sr_unix/util_output.c

Building with gcc 8.1.0 identified two types of warnings.
```
a) [-Wstringop-truncation] and
b) [-Wstringop-overflow=]
```
Example warnings
```
sr_unix/gtmcrypt_pk_ref.c:212:3: warning: 'strncpy' output truncated before terminating
nul copying as many bytes from a string as its length [-Wstringop-truncation]
sr_unix/gtmcrypt_dbk_ref.c:328:3: warning: 'strncpy' specified bound depends on the
length of the source argument [-Wstringop-overflow=]
```
Both warnings have to do with strncpy usages. The fix to strncpy usages was two-fold.
1) If "strncpy" is used to copy an exact number of bytes (e.g. if the exact number
was determined only a few lines above using strlen()), then the strncpy was replaced
with a memcpy since we don't need to do a copy looking for a terminating null byte.
2) If …

Fix various compiler warnings identified by gcc 8.1

---

sr_port/gbldefs.c
sr_port/handle_defered_signal.c
sr_port/have_crit.h
sr_port/t_end.c
sr_port/tp_tend.c
sr_unix/continue_handler.c
sr_unix/gt_timers.c
sr_unix/gtmsiginfo.h
sr_unix/rel_crit.c
sr_unix/rel_lock.c
sr_unix/suspend.c
sr_unix/suspsigs_handler.c

As part of a prior #215 commit, the DEFERRED_SIGNAL_HANDLING_CHECK macro was enhanced
to check for Ctrl-Z deferral. Turns out that change caused libyottadb.so size to bloat
from 5.00Mb (in r1.20) to 5.25Mb. This is because this macro is used in heavyweight
macros like REVERT which meant all the code inside this macro gets duplicated across
various parts of the compiled .o files thereby bloating the size of libyottadb.so (which
is just an aggregate of all the individual .o files).
To fix this size bloat, the macro was made minimalistic so it does a simple if check of
a global variable and if that is non-zero, in turn invoke a function that does most of
the code that was previously included in this macro. Thereby we centralize the code in
one place instead of inlining it everywhere the …

[#215] Trim down size of libyottadb.so more than it had bloated in prior #215 commit

---

CMakeLists.txt
sr_linux/release_name.h

This is to ensure a source build of the master branch clearly identifies
$zyrelease is different from r1.22.

Bump YottaDB release # from r122 to r123 now that r1.22 is released

---

sr_unix/ydbenv.mpt

Simple test case that illustrates the problem with the current mainline.
$ . /usr/local/lib/yottadb/r122/ydb_env_set
$ env | grep ydb_routines
ydb_routines=/usr/local/lib/yottadb/r122/libyottadbutil.so
But with r1.20, the same test shows ydb_routines with a lot more values
and these are needed for the "ydb" script to work fine.
$ . /usr/local/lib/yottadb/r120/ydb_env_set
$ env | grep ydb_routines
ydb_routines=/home/user/.yottadb/r1.20_x86_64/o*(/home/user/.yottadb/r1.20_x86_64/r /home/user/.yottadb/r) /usr/local/lib/yottadb/r120/libyottadbutil.so
With the fix, ydb_routines gets set to a value just like what it used to be in r1.20.

[#197] Fix regression in prior commit that caused ydb_routines to not be correctly set after ydb_env_set

---

CMakeLists.txt
sr_linux/release_name.h

This reverts commit 04c18105287b3cad2092ff8ebe591bf0ff98e665.
And is needed to rebuild r1.22 after a patch commit for #197

Revert "Bump YottaDB release # from r122 to r123 now that r1.22 is released"

---

sr_port/relqueopi.c
sr_port/shmpool.c
sr_port/sleep_cnt.h
sr_port/updhelper_reader.c
sr_unix/add_inter.c
sr_unix/ss_lock_facility.c

We have seen assert failures in debug builds in in-house testing on 1-CPU systems
(Raspberry Pi Zero and Beagblebone Black) in various tests occasionally.
The assert that fails is always the following.
%YDB-F-ASSERT, Assert failed in /Distrib/YottaDB/V999_R120/sr_port/relqueopi.c line 205
for expression (FALSE)
This is in the remqhi1() function when it has waited for 50 seconds to get the queue
header latch (GET_SWAPLOCK).
The 1-CPU systems that we have seen this failure on are slow boxes so this commit gives
such systems 4x the time (4 * 50 seconds) before signaling an assert failure.
In production builds, one would have gotten a DBCCERR error though we have not yet seen such
a failure in our in-house testing.
With the fix, the assert failure and DBCCERR error failures are expected to go …

Bump LOCK_TRIES from 50 seconds to 200 seconds (4x) on 1-CPU systems to address occasional test failures

---

sr_port/sleep_cnt.h

We have occasionally seen an assert failure in debug builds in in-house testing on the
Raspberry Pi Zero (a 1-CPU system).
```
%YDB-F-ASSERT, Assert failed in /Distrib/YottaDB/V998_R122/sr_port/wcs_phase2_commit_wait.c
line 337 for expression (cnl->wc_blocked
|| (WBTEST_CRASH_SHUTDOWN_EXPECTED == ydb_white_box_test_case_number))
```
The update helper reader process waited 1 minute for a specific cache-record in phase2 commit
to be freed up by the update process and timed out.
The 1-CPU system that we have seen this failure is a slow box so this commit gives
such systems 4x the time (4 minutes) before signaling an assert failure.
In production builds, this was a non-issue since the timeout would have returned FALSE from
wcs_phase2_commit_wait() which in turn would have triggered a …

Bump PHASE2_COMMIT_WAIT from 1 minute to 4 minutes (4x) on 1-CPU systems to address occasional test failures

---

sr_port/repl_filter.c

Not doing so could cause the source server to loop indefinitely in case the filter program
terminates prematurely.

[#264] Handle return value of 0 from read() i.e. EOF on pipe fd

---

sr_port/merrors.msg
sr_port/merrors_ctl.c

All current usages of DBFILOPERR error pass the database file name (not the region) so no
other change needed in the callers of DBFILOPERR.

Fix DBFILOPERR message text to say database file (instead of region) as it is the file name that is printed (not the region name)

---

sr_port/wbox_test_init.h
sr_unix/iott_use.c

This fixes an occasional v63003/gtm8787 subtest failure due to an assert failure at line 457 below.
```c
iott_use.c
454  Tcsetattr(tt_ptr->fildes, TCSANOW, &t, status, save_errno);
455  if (0 != status)
456  {
457          assert(FALSE);
458          rts_error_csa(CSA_ARG(NULL) VARLSTCNT(4) ERR_TCSETATTR, 1, tt_ptr->fildes, save_errno);
459  }
```
In the gtm8787 subtest, the terminal is killed so the error from Tcsetattr() (save_errno = 5/EIO)
is not unexpected. To work around the assert failure, check for a specific white-box case (the newly
introduced WBTEST_KILL_TERMINAL case) and if so skip the assert.
While modifying iott_use.c, noticed a ISSUE_NOPRINCIO_IF_NEEDED_TT usage in case tcgetattr() call on
the terminal fd fails. I don't see the need for this call to issue NOPRINCIO error. …

Do not assert fail in case tcsetattr() call fails and a white-box case indicates terminal is killed

---

sr_port/iosocket_close.c
sr_port/iosocket_create.c
sr_port/iosocket_open.c

* sr_port/iosocket_create.c :
In case the JOB command specifies an INPUT/OUTPUT/STDERR that is a socket handle,
iosocket_create() would be invoked by the jobbed off process as part of io_init()
when it detects that its principal device is a socket. This code was assuming
that the socket is a CONNECTED socket when in fact it could be a LISTENING socket
too (nothing in the code currently prevents a LISTENING socket from being passed
around). But since the initialization in iosocket_create() happened as if the
socket is a connected socket, a later iosocket_wait() call (when a WRITE /WAIT is
done) will not do the right calls (a listening socket needs to do an accept() call).
The fix for this is to set the socketptr->state to "socket_listening" instead of
"socket_connected" based on what …

[#275] Allow LISTENING sockets to be passed to other processes without hanging (through JOB command or LOCAL socket passing)

---

sr_port/cre_jnl_file.c
sr_port/cre_jnl_file_intrpt_rename.c
sr_port/gtmsource_ctl_init.c
sr_port/jnl.h
sr_port/wbox_test_init.h
sr_unix/iott_use.c
sr_unix/jnl_file_open.c

See issue description at YottaDB/YottaDB#282 for background. The crux of the fix is to
sr_port/cre_jnl_file_intrpt_rename.c and sr_port/gtmsource_ctl_init.c. The function
cre_jnl_file_intrpt_rename() now returns a status (previously it was void) and its return
value is used to determine whether special action needs to be taken in case of the source server.
In order to test these error scenarios, two white-box cases were introduced. And to
avoid collision with GTM introduced wbox codes, the YottaDB white-box codes start at 200
which gives a gap of 60 codes that should be ample enough a gap for a few years at least.

[#282] Enhance source server to handle FILEDELFAIL and RENAMEFAIL error scenarios in a user-friendly fashion

---

sr_port/updproc.c

SET $ZGBLDIR inside a trigger does the switch the first time. That changes the dollar_zgbldir.str
mstr to point to the new global directory. But once the trigger returns, the update process
switched gd_header back to what it was before the trigger was invoked (done as part of GTM-8789
in GT.M V6.3-003). But this does not switch dollar_zgbldir.str back to point to the original
gbldir. This out-of-sync situation means that future trigger invocations that do the SET $ZGBLDIR
to the same new global directory as before will incorrectly conclude (in op_svput) that
dollar_zgbldir.str already points to the gbldir of interest and so return prematurely. This means
that updates which happen inside the trigger will go to the original gbldir (with which the update
process started) and not the gbldir …

[#293] SET $ZGBLDIR inside a trigger does not switch global directories in the update process

---

sr_port/op_zst_break.c
sr_port/op_zstep.c

GTM-8842 fixed this issue in GT.M V6.3-003 but the fix seems incorrect. The change was
done in op_set_zbreak() to return if we are inside a trigger. But by the time op_set_zbreak()
is invoked, the transfer table has already been changed by op_zstep.c in preparation for
the ZSTEP action. This undo happens much later when op_set_zbreak() is called after we
finish executing the trigger at which point, the current $ZSTEP action is executed too.
This is an unintended side effect which is considered incorrect. A ZSTEP action which was
ignored while inside a trigger should continue to be ignored after exiting the trigger too.
The fix is to remove the change done in op_set_zbreak() but move that check to op_zstep.c
so we do not do any transfer table change while inside a trigger and if …

[#295] ZSTEP inside trigger should be ignored completely if TRIGGER_MOD restriction is in place

---

sr_port/mlk_shrblk_create.c
sr_port/mlk_shrblk_delete_if_empty.c
sr_port/mlk_shrblk_find.c
sr_port/mlkdef.h
sr_port/tab_bg_trc_rec.h

See description at https://github.com/YottaDB/YottaDB/issues/297 for background on issue.
As for a fix, the hopscotch algorithm is modified to use 31 as H (instead of 32). So there will
be 31 neighbor buckets instead of 32 buckets. The highbit (bit 31) is set whenever we end up with
a situation where all neighbor buckets are full when we try to add a key to the mlk_shrhash table.
If we find the highbit set, we do a linear search of the entire hash buckets array instead
of just the 31 neighbor buckets to check if a key exists or not. A similar logic is used for
deletion of an entry from the mlk_shrhash table too.
This modified hopscotch algorithm handles the bucket-full situation (a very rare scenario) with a
slower linear search. It still continues to use the much faster hash algorithm …

[#297] LOCK commands can spin-loop/hang and incorrectly seize ownership in rare cases

---

sr_unix/zro_search.c

Below is a simple test case with a debug build of YottaDB.
```
> cat y.m
write "version 1",!
> setenv ydb_routines ".* $ydb_dist"
> $gtm_dist/mumps -run %XCMD 'zlink "y^1" do ^y'
%YDB-E-ZLINKFILE, Error while zlinking "y^1"
%YDB-E-FILENOTFND, File y^1 not found
> setenv ydb_routines ".* $ydb_dist $ydb_dist/plugin/libgtmposix.so"
> $gtm_dist/mumps -run %XCMD 'zlink "y^1" do ^y'
%YDB-F-ASSERT, Assert failed in sr_unix/zro_search.c line 104 for expression (valid_mname(&rtnname))
```
This proves that we cannot assert on the validity of a routine name in the code where we
process a shared library specification in the $zroutines list. That debug-only code is therefore removed.

Remove assert in zro_search.c that fails if invalid routine name is specified when $zroutines has a .so file in its list

---

sr_port/get_log_name.c
sr_port/io.h
sr_unix/iopi_open.c

In the v62001/gtm8094pipproc subtest, a recent test enhancement to print the complete DEVOPENFAIL
syslog message resulted in an occasional test failure where the device name was printed as garbage.
For example,
Expected message was
%YDB-E-DEVOPENFAIL, Error opening uname,
%YDB-I-TEXT, PIPE - dup2(pfd_write[0]) failed in child, %SYSTEM-E-UNKNOWN, Unknown system error 0
Actual message was
%YDB-E-DEVOPENFAIL, Error opening .......$...............q5............. .......q......,
%YDB-I-TEXT, PIPE - dup2(pfd_write[0]) failed in child, %SYSTEM-E-UNKNOWN, Unknown system error 0
This turned out to be a longstanding code issue in iopi_open.c.
In the forked off child process in iopi_open(), there are various places where system calls
could error out. In that case, we issue a DEVOPENFAIL error to …

[#310] Garbage device name in DEVOPENFAIL message in syslog after an error in OPEN of a PIPE device

---

sr_port/get_cmd_qlf.c

op_zcompile and gtm_compile call zl_cmd_qlf() twice. Once to set the compilation
flags based on $ZCOMPILE (derived from env vars ydb_compile/gtmcompile) and again to set
the compilation flags based on what has been explicitly specified by the user (in the
ZCOMPILE command line or the MUMPS command line). The second invocation of zl_cmd_qlf()
is supposed to override any conflicting flags specified in the previous invocation.
But for the WARNINGS case, get_cmd_qlf() was checking if -NOWARNINGS was specified and
if so negating the corresponding flag (~CQ_WARNINGS) but in the else case it was
not checking if -WARNINGS was explicitly specified. It was setting the warning flag
to CQ_WARNINGS even if -WARNINGS was not explicitly specified. This meant that the
-NOWARNINGS specified in $ZCOMPILE …

[#315] ZCOMPILE should not issue warnings if $ZCOMPILE is set to "-nowarnings"

---

sr_port/iosocket_iocontrol.c

The v63002/gtm8165 subtest created a scenario where TPNOTACID messages were sent to the syslog
for a variety of command usages. For commands like HANG, LOCK or OPEN, it clearly indicated the name
of the command that caused the message. An example message for the OPEN command is the below
%YDB-I-TPNOTACID, OPEN at opentimeout+5^gtm8165 violates ACID properties of a TRANSACTION and could exceed .123 seconds;
But when the command causing the TPNOTACID was a WRITE /WAIT or a WRITE /PASS or WRITE /ACCEPT
or WRITE /TLS, the message read as follows
%YDB-I-TPNOTACID, FORMAT at writeslashpass+14^gtm8165 violates ACID properties of a TRANSACTION and could exceed .123 seconds;
Note the word FORMAT. I guess this is intended to indicate that a command involving a format character
"/" was used. But it …

Make TPNOTACID message more informative in case of /WAIT, /PASS, /ACCEPT or /TLS usages

---

sr_unix/jnlpool_init.c

In this subtest, we do a jnlpool_init(GTMRELAXED) for a read access because ydb_custom_errors/gtm_custom_errors
env var is set. But the jnlpool is not set up yet. And so the jnlpool_init(GTMRELAXED) call allocates a
"jnlpool" structure but has a "jnlpool_ctl" pointer set to NULL when it returns. Later the test
starts the source server (using a zsystem) and then attempts an update on a database. This does a
jnlpool_init(GTMPROC) call which finds the previously allocated "jnlpool" structure and reuses it correctly
but has an assert that the jnlpool pointer from the gld should be NULL. It is not NULL due to the prior
jnlpool_init(GTMRELAXED) call. The fix is to add an || condition which verifies this particular scenario.

[#312] Fix assert that is not accurate in one case exposed by r124/ydb312_gtm8182d subtest

---

sr_port/restrict.c

The check for whether one file is newer than the other was done as follows in a prior commit.
(rmtime.tv_sec > fmtime.tv_sec) || (rmtime.tv_nsec >= fmtime.tv_nsec)
But this will result in a false evaluation in the case rmtime.tv_sec < fmtime.tv_sec but
rmtime.tv_nsec > fmtime.tv_nsec. That is what happened in an in-house test on the Raspberry Pi
boxes which caused the filter_commands.tab file to be recreated in the middle of adding lines
from a multi-line restrict.txt file.
The check is now corrected to read as follows
(rmtime.tv_sec > fmtime.tv_sec) || (rmtime.tv_sec == fmtime.tv_sec) && (rmtime.tv_nsec >= fmtime.tv_nsec)
With this check, the test reliably passes on the Pi boxes.

[#318] Fix incorrect time check in prior commit of sr_port/restrict.c

---

sr_port/mstack_size_init.c

The V6.3-005 release notes had the following mention about GTM-5059.
```
GT.M recognizes setting the environment variable gtm_mstack_crit_threshold to specify an integer
between 15 and 95 defining the percentage of the stack which should be used before GT.M emits a
STACKCRIT warning. If the value is below the minimum or above the maximum GT.M uses the minimum or
maximum respectively. The default is 90.
```
But in testing, we found that when gtm_mstack_crit_threshold env var is set to 0, the default is
assumed whereas the release note indicates the minimum will be assumed (because 0 is less than the
minimum of 15). The code is now fixed to match the release note so if the env var is set to 0,
the minimum of 15 is assumed.

[GTM-5059] Fix code to match V6.3-005 release note when gtm_mstack_crit_threshold env var is set to 0

---

sr_port/mdb_condition_handler.c
sr_port/trans_code_cleanup.c

The way direct mode check was done in mdb_condition_handler() was to check if the frame
immediately previous to the current frame is a direct-mode frame (SFT_DM) or if we are in compile
time and if so check if the current frame is a direct-mode frame. This meant that if an error
occurs inside an indirection usage (which translates to an arbitrary number of uncounted frames
underneath the SFT_DM frame), we would end up treating that error as coming from a non-direct-mode
action which is inconsistent since the same error outside of the indirection will be treated as if
it happened in direct-mode. This inconsistency is fixed by checking all frames back from the current
one until we see either a counted frame or a SFT_DM frame. And using that to decide whether we
are in direct mode or not. …

[#324] Error inside indirection usage in direct mode using $ETRAP (not $ZTRAP) causes process to incorrectly terminate

---

sr_port/jnl2ext.c

External filters (invoked from either the source or receiver server) are provided the
journal record in the journal extract format. Until now, the timestamps in the journal
extract format was zeroed out before passing it to the external filter program. But some
filters might find the need for the timestamp to decide how to act on the journal record
so pass the non-zero timestamp (in $HOROLOG format) to the external filter unconditionally.

[#321] Journal records fed to replication filters (external filters) include timestamps

---

sr_port/restrict.c

We had a v63005/gtm8877 subtest failure where line 50 below issued a COMMFILTERERR error.
```
gtm8877.csh
-----------
42 # FILTER RETURNING A STRING
43 rm $ydb_dist/restrict.txt
44 cat > $ydb_dist/restrict.txt << EOF
45 ZSYSTEM_FILTER:filterfn2^gtm8877
46 PIPE_FILTER:filterfn2^gtm8877
47 EOF
48 chmod -w $ydb_dist/restrict.txt
49 echo "# FILTER RETURNING A STRING"
50 $ydb_dist/mumps -run zsystemfn^gtm8877
51 $ydb_dist/mumps -run pipeopenfn^gtm8877
52 echo ""
Expected output
---------------
filtered output
filtered output
Actual output
-------------
%YDB-E-COMMFILTERERR, Error executing the command filter for gtmzsystem. 150379666,(Call-In),%YDB-E-CINOENTRY, No entry specified for gtmzsystem in the call-in table
filtered output
```
We clearly added ZSYSTEM_FILTER just before PIPE_FILTER in …

[#318] Create filter_commands.tab at most once while scanning multiple lines of restrict.txt

---

sr_port/od.mpt
sr_port/oh.mpt

This was mentioned as having been fixed in GTM-5574 in GT.M V6.3-005 but we noticed during testing
that it was not. Only %OD and %OH seemed to have the NUMOFLOW issue. The others (e.g. %HO, %HD etc.)
worked fine.

[GTM-5574] Fix %OD and %OH to not issue incorrect NUMOFLOW error in case a huge octal number (>= 10**47) is specified

---

sr_port/t_end.c
sr_port/tp_tend.c
sr_port/updhelper_writer.c
sr_unix/wcs_flu.c

Code fixes for GTM-8708 in GT.M V6.3-002 wanted to prevent the update helper writer process from
unnecessarily making calls to grab_crit_immediate() in case the instance had no updates.
It did this by setting the next epoch time (jbp->next_epoch_time) to a huge value (MAXUINT4)
the moment a wcs_flu() call was done to write a regular epoch (JRE gvstat) where it noticed an
idle epoch (JRI gvstat) had already been written (because of inactivity since the last update).
This caused the jbp->next_epoch_time vs jgbl.gbl_jrec_time check in updhelper_writer() to
automatically skip invoking the grab_crit_immediate() during periods of idleness.
But this introduced the #341 regression. It is now possible for a regular epoch to not be written
in a timely fashion. This is because once …

[#341] epoch_interval setting in the journal file needs to be honored in all cases
